### ISSUE TITLE
16. Kunder ska kunna få nyhetsbrev genom att ange namn och email.

### ISSUE THREAD

**Issue by wictoriadrefelt** [AminaHallam/Webshop#18]
Man ska från hemsidan kunna skriva upp sig för att få butikens nyhetsbrev genom att ange sitt namn och epostadress (G)

MYSQL-förslag: 
Utifrån: 
INSERT INTO `subscriptionnews` (FirstName, LastName, Email) 
VALUES ('Amina', 'Hallam', 'aminahallam@live.se')

Med konto: 
INSERT INTO subscriptionnews(UserID, FirstName, LastName, Email)
SELECT UserID, FirstName, LastName, Email
FROM user u
where u.UserID = 1

**Comment by AminaHallam** [comment]
Create-NewsLetter-box
