### ISSUE TITLE
9. Hashning av lösenord

### ISSUE THREAD

**Issue by wictoriadrefelt** [AminaHallam/Webshop#9]
Inga Lösenord får sparas i klartext i databasen (G)

**Comment by LisaKarnerfors** [comment]
Länk till inspelningen 3/2

https://medieinstitutet-my.sharepoint.com/:v:/g/personal/lisa_karnerfors_medieinstitutet_se/EV2fUajFpKVMq1-ldBN94fcBsKot6-n9FF3dxAUt6z1Kcw
